### PR TITLE
Added some tests for the Themer class

### PR DESCRIPTION
**Pull request by parithon**
# Purpose

We need tests to ensure that stuff doesn't break when new features are introduced. Included in this PR are tests specific to the Themer class (which actually makes the changes to the vscode configuration).

# Added
- **themer.test.ts** The Themer test suite.
  - Themer should return current theme (Visual Studio Dark)
  - Themer should reset theme to theme used when extension is activated
  - Themer should change current theme to Default Dark+
  - Themer should return a comma seperated list of themes
  - Themer should ban a user
  - Themer should unban a user
  - Themer should not ban if user is not the logged in user
  - Themer should not unban if user is not the logged in user

# Changed
- **Themer.ts** I needed to add async functionally to ensure the promises would complete prior to tests continuing.
- **package.json** Added some npm packages for testing utilities such as 'sinon' for stubs and 'chai' for better assertions.

# Addresses

Partially address #3

bitmoji

### CODE REVIEW

**Comment by MichaelJolley** [comment]
@all-contributors please add @parithon for tests

**Comment by MichaelJolley** [comment]
bitmoji

**Comment by sorskoot** [comment]
Does this PR close #3 ?

**Comment by MichaelJolley** [comment]
@sorskoot I don't think so.  It added a framework and some tests, but not all tests.  I've actually pulled it down and added some tests for the new follower only mode.  Feel free to pull the vNext branch and look for any missing tests.

**Pull request merged**
